### ISSUE TITLE
0% Opacity Bug

### ISSUE THREAD

**Issue by Babipoki** [cirrahn/foundry-polmap#2] opened 2022-04-28 09:50 UTC
Heyo! I love this plugin, but I've come to an issue.

Since I need to have polmap turned off to check on the colors of the map I'm painting, I need to set the opacity of polmap to 0%. The problem arises when you switch from that scene to another and then return - the opacity sets itself back to 50%.

Hope it can be fixed easily and isn't much of a hassle.

**Comment by cirrahn** [comment] 2022-05-03 17:51
I cannot reproduce this issue. Could you provide screenshots or a video of you experiencing it?

As a workaround, have you tried disabling the overlay while working on your color-sensitive task? There is a "toggle layer" button for this reason.

**Comment by Babipoki** [comment] 2022-05-03 18:33
I worded things incorrectly.
To reproduce:

1. Set GM/player opacity to 0%
2. Go to another scene
3. Return to this one
4. As a result, the opacity will be set to default 50%

It might be related to other modules or my system if this is not reproductible on your end. Regardless, toggling the polmap layer works just fine too!

**Comment by cirrahn** [comment] 2022-05-13 14:16
Sorry for not getting back to this sooner. Should be fixed in v1.0.1!

**Closed as completed by cirrahn** 2022-05-13 14:16 UTC
Labels: bug, norepro
